version: "3.7"

services:
  kafka:
    hostname: kafka
    image: docker.io/apache/kafka:3.7.0
    ports:
      - "9092:29092"
    environment:
      - "KAFKA_NODE_ID=1"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092"
      - "KAFKA_LISTENERS=CONTROLLER://:29093,PLAINTEXT://:9092,PLAINTEXT_HOST://:29092"
      - "KAFKA_PROCESS_ROLES=broker,controller"
      - "KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER"
      - "KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:29093"
    volumes:
      - "oci_kafka_data:/var/lib/kafka/data"

volumes:
  oci_kafka_data:
    name: "{COMPOSE_PROJECT_NAME}_kafka"